import accountingHero from '../../assets/accounting-hero.jpg'
import { SiteFooter } from '../../components/site/SiteFooter'
import { SiteHeader } from '../../components/site/SiteHeader'
import '../services/ServicePages.css'

export default function AccountingPage() {
  return <div className="service-page">
    <SiteHeader active="accounting" />
    <main>
      <section className="accounting-hero"><div className="page-container accounting-hero-grid"><div><span className="service-kicker">Professional Services</span><h1>Strategic Accounting for Global Enterprises.</h1><p>We deliver authoritative financial clarity through rigorous data integrity and strategic foresight. Transform your accounting from a cost center into a strategic engine.</p><div className="service-actions"><a className="service-button primary" href="#inquiry">Talk to an Expert</a><a className="service-button outline" href="/#mission">View Our Mission</a></div></div><img src={accountingHero} alt="Financial analysis displayed beside an accounting ledger" /></div></section>
      <section className="service-section"><div className="page-container"><div className="service-heading"><h2>Core Accounting Pillars</h2><p>Precision-engineered financial services tailored for high-stakes business environments.</p></div><div className="accounting-grid">
        <article className="service-card wide"><div className="service-icon">▣</div><h3>Strategic Tax Planning</h3><p>Our tax specialists navigate complex global jurisdictions to optimize your fiscal position while ensuring full regulatory compliance.</p><ul className="feature-list"><li>Multi-jurisdictional Optimization</li><li>R&amp;D Tax Credit Advisory</li><li>M&amp;A Tax Due Diligence</li><li>Corporate Structure Analysis</li></ul><a className="small-link" href="#inquiry">Explore Strategies →</a></article>
        <article className="service-card narrow"><div className="service-icon">▤</div><h3>Bookkeeping</h3><p>Continuous, real-time ledger management powered by advanced automated reconciliation and human oversight.</p><a className="small-link" href="#inquiry">Manage Ledgers →</a></article>
        <article className="service-card narrow"><div className="service-icon">⌁</div><h3>IFRS Compliance</h3><p>Maintain gold-standard transparency with International Financial Reporting Standards adherence.</p><a className="small-link" href="#inquiry">View Standards →</a></article>
        <article className="service-card wide"><div className="service-icon">↗</div><h3>Financial Reporting</h3><p>Go beyond basic statements. Our reporting delivers deep-dive analytics into cash flow, profitability by segment, and predictive variance analysis.</p><div className="metric-row"><div><strong>100%</strong><br/>Accuracy</div><div><strong>Real-time</strong><br/>Access</div><div><strong>Custom</strong><br/>Dashboards</div></div></article>
      </div></div></section>
      <section className="service-section accounting-cta" id="inquiry"><div className="page-container accounting-cta-grid"><div><h2>Ready to secure your financial future?</h2><p>Join the hundreds of global firms that trust BABCS Corp for their critical accounting and tax architecture.</p><a className="service-button dark" href="mailto:inquiries@babcs.example">Talk to an Expert</a></div><form className="quick-form" onSubmit={event=>event.preventDefault()}><strong>Quick Inquiry</strong><input aria-label="Full name" placeholder="Full Name" required/><input aria-label="Corporate email" type="email" placeholder="Corporate Email" required/><select aria-label="Service"><option>Strategic Tax Planning</option><option>Bookkeeping</option><option>IFRS Compliance</option></select><button className="service-button primary" type="submit">Send Request</button></form></div></section>
      <section className="service-section"><div className="page-container"><div className="service-heading"><h2>Our Methodology</h2></div><div className="method-grid">{[['1','Diagnostic','Comprehensive audit of current financial systems.'],['2','Structuring','Customized framework development for your entity.'],['3','Execution','Seamless transition and daily management integration.'],['4','Review','Monthly strategy sessions and performance tuning.']].map(([n,t,p])=><div key={n}><strong>{n}</strong><span>{t}</span><p>{p}</p></div>)}</div></div></section>
    </main><SiteFooter />
  </div>
}
