import missionCeo from '../../assets/mission-ceo.jpg'
import missionClarity from '../../assets/mission-clarity.jpg'
import missionHeadquarters from '../../assets/mission-headquarters.jpg'
import { SiteFooter } from '../../components/site/SiteFooter'
import { SiteHeader } from '../../components/site/SiteHeader'
import '../services/ServicePages.css'

export default function MissionPage() {
  const milestones = [['2010 — Foundation','The Birth of Clarity','BABCS Corp was founded with a single mission: to bring institutional-grade auditing to emerging markets with total transparency.'],['2015 — Expansion','Strategic Diversification','Launched our HR and IT Advisory divisions, integrating human capital strategy with technological infrastructure.'],['2021 — Innovation','AI-Driven Audit Protocols','Pioneered machine learning models for real-time risk assessment, reducing audit turnaround times while increasing accuracy.'],['Today — Leadership','A Global Authority','Operating in 14 countries, BABCS Corp is recognized as the gold standard for strategic professional services.']]
  return <div className="service-page mission-page"><SiteHeader active="mission"/><main>
    <section className="service-section"><div className="page-container mission-page-hero"><div><span className="service-kicker">Our Foundation</span><h1>Structural Clarity in a Complex World.</h1><p>At BABCS Corp, we believe that authority is built on transparency. Our mission is to provide the rigorous framework and strategic insight required for global enterprises to grow with unwavering confidence.</p><div className="mission-values"><span>Strategic</span><span>Transparent</span><span>Authoritative</span></div></div><img src={missionHeadquarters} alt="Modern corporate headquarters"/></div></section>
    <section className="service-section mission-pillars"><div className="page-container"><div className="service-heading"><h2>The Pillars of Our Commitment</h2></div><div className="mission-pillar-grid"><article className="service-card wide"><div className="service-icon">▥</div><h3>Structural Integrity</h3><p>We design systems that withstand the pressures of global market fluctuations. Our accounting and audit frameworks are built on a foundation of absolute precision and regulatory compliance.</p></article><article className="service-card"><div className="service-icon">✦</div><h3>Innovation</h3><p>Leveraging AI and predictive analytics to transform retrospective auditing into prospective strategy.</p></article><article className="service-card"><div className="service-icon">◯</div><h3>Sustainable Growth</h3><p>Focusing on long-term viability over short-term gains, ensuring our clients build legacies that last generations.</p></article><article className="service-card wide clarity-card"><div><div className="service-icon">⊙</div><h3>Radical Transparency</h3><p>Clear communication and open reporting are not just features; they are the core of our authoritative presence.</p></div><img src={missionClarity} alt="Bright, precise professional workspace"/></article></div></div></section>
    <section className="service-section"><div className="page-container evolution-grid"><aside><h2>Our Evolution</h2><p>A timeline of milestones that define our journey from a specialized audit boutique to a global leader in professional services.</p><div className="assets-card"><span>Total Assets Managed</span><strong>$4.2T+</strong></div></aside><div className="timeline">{milestones.map(([date,title,copy])=><article key={date}><span>{date}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="leader-section"><div className="page-container leader-grid"><div className="leader-image"><img src={missionCeo} alt="BABCS chief strategy officer"/><div><strong>Alistair Thorne</strong><span>Chief Strategy Officer</span></div></div><div><b className="quote-mark">”</b><h2>&quot;Integrity is the only structural element that cannot be replaced.&quot;</h2><p>The future of professional services isn&apos;t just about data; it&apos;s about the trust placed in that data. At BABCS Corp, we don&apos;t just provide answers—we provide the certainty that allows our partners to dream larger and act bolder.</p><a className="service-button outline" href="#report">Read the Annual Report</a></div></div></section>
    <section className="service-section mission-cta"><div className="page-container"><h2>Ready for Structural Clarity?</h2><p>Connect with our executive consultants today to discuss how BABCS Corp can fortify your business for sustainable, global growth.</p><a className="service-button dark" href="/inquire">Consult an Expert</a></div></section>
  </main><SiteFooter/></div>
}
