import auditCta from '../../assets/audit-cta.jpg'
import auditHero from '../../assets/audit-hero.jpg'
import { SiteFooter } from '../../components/site/SiteFooter'
import { SiteHeader } from '../../components/site/SiteHeader'
import '../services/ServicePages.css'

export default function AuditPage() {
  return <div className="service-page audit-page"><SiteHeader active="audit"/><main className="page-container">
    <section className="audit-hero"><div><span className="service-kicker audit-kicker">Strategic Assurance</span><h1>Precision-Engineered Audit &amp; Compliance</h1><p>Navigating complex regulatory landscapes with authority. We provide the structural clarity required for high-stakes financial and operational stability.</p><div className="service-actions"><a className="service-button dark" href="#contact">Request Audit Survey →</a></div></div><img src={auditHero} alt="Modern corporate boardroom overlooking a city"/></section>
    <section className="service-section"><div className="audit-heading"><div><h2>Our Core Competencies</h2><p>Specialized assurance frameworks for the modern C-suite.</p></div></div><div className="audit-grid">
      <article className="service-card wide"><div className="service-icon">▥</div><h3>Internal Audits</h3><p>Comprehensive evaluation of internal controls, risk management, and governance processes. Our objective is to improve organizational efficiency and provide reliable data for decision-making.</p><div className="metric-row"><div>Focus Area<br/><strong>Asset Protection</strong></div><div>Methodology<br/><strong>COSO Framework</strong></div><div>Output<br/><strong>Strategic Roadmap</strong></div></div></article>
      <article className="service-card narrow"><div className="service-icon">⌁</div><h3>Regulatory Compliance</h3><p>Ensuring your operations align with local and international statutory requirements.</p><ul className="feature-list" style={{gridTemplateColumns:'1fr'}}><li>SEC/FINRA Alignment</li><li>GDPR &amp; Data Privacy</li><li>ESG Disclosures</li></ul></article>
      <article className="service-card half"><div className="service-icon">▥</div><h3>Risk Assessment</h3><p>Predictive modeling and vulnerability scanning to identify systemic risks before they impact your bottom line.</p><div className="metric-row" style={{gridTemplateColumns:'1fr'}}><div>Real-Time Risk Monitor<br/><span>Awaiting Parameters...</span></div></div></article>
      <article className="service-card half audit-dark"><div className="service-icon">◉</div><h3>Transparency Reporting</h3><p>Modern stakeholder communication through rigorous, data-driven transparency reports that build investor trust.</p><div className="audit-tags"><span>Board-Ready Docs</span><span>Interactive Dashboards</span><span>Audited Truth</span></div></article>
    </div></section>
    <section className="audit-stats"><div><strong>$12B+</strong><span>Assets Audited</span></div><div><strong>500+</strong><span>Statutory Clients</span></div><div><strong>15+</strong><span>Global Jurisdictions</span></div><div><strong>0</strong><span>Compliance Failures</span></div></section>
    <section className="service-section"><div className="service-heading"><h2>The BABCS Assurance Lifecycle</h2></div><div className="lifecycle-grid">{[['1','Discovery','Mapping operational complexity and identifying critical control points.'],['2','Execution','Rigorous field-testing and substantive verification of transaction flows.'],['3','Verification','Multi-layered peer review ensuring the highest levels of accuracy.'],['✓','Certification','Issuance of high-authority audit opinions and compliance seals.']].map(([n,t,p])=><div key={t}><strong>{n}</strong><b>{t}</b><p>{p}</p></div>)}</div></section>
    <section className="service-section" id="contact"><div className="audit-cta"><img src={auditCta} alt="Corporate headquarters architecture"/><div className="audit-cta-content"><h2>Ready to fortify your business foundations?</h2><p>Our partners are ready to discuss your unique audit requirements in a confidential, strategic session.</p><div className="service-actions"><a className="service-button primary" href="mailto:inquiries@babcs.example">Schedule Consultation</a><a className="service-button outline" href="#competencies">Download Service Guide</a></div></div></div></section>
  </main><SiteFooter/></div>
}
